include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    prefer_asserts_with_message: ignore
    public_member_api_docs: ignore
    return_of_invalid_type: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'