name: mostaqem
description: An islamic audio app
publish_to: none
version: "2.2.1+1"

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: "^3.3.1"
  crypto: ^3.0.5
  device_info_plus: "^10.1.0"
  dio: "^5.4.3+1"
  flutter_discord_rpc: ^1.0.0
  file_picker: "^8.0.6"

  flutter:
    sdk: flutter

  flutter_cache_manager: "^3.3.1"
  flutter_colorpicker: "^1.1.0"

  flutter_localizations:
    sdk: flutter

  flutter_riverpod: "^2.5.1"
  flutter_svg: "^2.0.10+1"
  freezed: "^2.5.2"
  freezed_annotation: "^2.4.1"
  launch_at_startup: ^0.3.1
  github: "^9.24.0"
  go_router: "^14.1.4"
  google_fonts: "^6.2.1"
  hijri: "^3.0.0"
  internet_connection_checker: "^1.0.0"
  json_annotation: "^4.9.0"
  lrc: "^1.0.2"
  media_kit: "^1.1.11"
  media_kit_libs_audio: "^1.0.5"
  metadata_god: ^1.0.0
  mpris_service:
    git: "https://github.com/alexmercerind/mpris_service"
  package_info_plus: "^8.0.0"
  path_provider: "^2.1.3"
  riverpod_annotation: "^2.3.5"
  rxdart: ^0.28.0
  shared_preferences: "^2.2.3"
  smtc_windows: ^1.0.0
  url_launcher: "^6.3.0"
  window_manager: "^0.3.9"
  windows_taskbar: "^1.1.2"
  context_menus: ^2.0.0+1

dev_dependencies:
  build_runner: "^2.4.14"
  custom_lint: ^0.7.1
  flutter_lints: "^3.0.0"
  flutter_test:
    sdk: flutter
  json_serializable: "^6.8.0"
  msix: "^3.16.8"
  pubspec_dependency_sorter: "^1.0.4"
  riverpod_generator: "^2.4.0"
  riverpod_lint: "^2.3.12"
  very_good_analysis: "^6.0.0"

msix_config:
  display_name: Mostaqem
  publisher_display_name: "Mostaqem, Inc"
  identity_name: MostaqemInc.Mostaqem
  publisher: "CN=5EE089E6-BF1D-4AF3-AD61-23B736E7D130"
  msix_version: 2.2.1.0
  logo_path: 'D:\\Projects\\Mostaqem\\mostaqem\\assets\\img\\app_icon.png'
  capabilities: internetClient
  store: true

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/quran/

