name: mostaqem
description: An islamic audio app
publish_to: none
version: "2.3.0+1"

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: "^3.4.1"
  crypto: ^3.0.6
  device_info_plus: "^11.4.0"
  dio: "^5.8.0+1"
  flutter_discord_rpc: ^1.0.0
  file_picker: "^10.1.7"
  ffi: ^2.1.4
  flutter:
    sdk: flutter

  flutter_cache_manager: "^3.4.1"
  flutter_colorpicker: "^1.1.0"

  flutter_localizations:
    sdk: flutter

  flutter_riverpod: "^2.6.1"
  freezed: "^3.0.6"
  freezed_annotation: "^3.0.0"
  launch_at_startup: ^0.5.1
  github: "^9.25.0"
  go_router: "^15.1.2"
  google_fonts: "^6.2.1"
  hijri: "^3.0.0"
  internet_connection_checker: "^3.0.1"
  json_annotation: "^4.9.0"
  lrc: "^1.0.2"
  media_kit: "^1.2.0"
  media_kit_libs_audio: "^1.0.6"
  metadata_god: ^1.0.0
  mpris_service:
    git: "https://github.com/alexmercerind/mpris_service"
  package_info_plus: "^8.3.0"
  path_provider: "^2.1.5"
  riverpod_annotation: "^2.6.1"
  rxdart: ^0.28.0
  shared_preferences: "^2.5.3"
  smtc_windows: ^1.0.0
  url_launcher: "^6.3.1"
  window_manager: "^0.4.3"
  windows_taskbar: "^1.1.2"
  context_menus: ^2.0.0+1
  vector_graphics: ^1.1.18
  flutter_single_instance: ^1.5.0
  lottie: ^3.3.1
  youtube_explode_dart: ^2.4.2
  
dev_dependencies:
  build_runner: "^2.4.14"
  custom_lint: ^0.7.5
  flutter_lints: "^5.0.0"
  flutter_test:
    sdk: flutter
  json_serializable: "^6.9.5"
  msix: "^3.16.9"
  pubspec_dependency_sorter: "^1.0.5"
  riverpod_generator: "^2.6.5"
  riverpod_lint: "^2.6.5"
  very_good_analysis: "^7.0.0"
  vector_graphics_compiler: ^1.1.16

msix_config:
  display_name: Mostaqem
  publisher_display_name: "Mostaqem, Inc"
  identity_name: MostaqemInc.Mostaqem
  publisher: "CN=5EE089E6-BF1D-4AF3-AD61-23B736E7D130"
  msix_version: 2.3.0.0
  logo_path: 'D:\\Projects\\Mostaqem\\mostaqem\\assets\\img\\app_icon.png'
  capabilities: internetClient
  store: true

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - path: assets/img/svg/
      transformers:
        - package: vector_graphics_compiler

    - assets/quran/

