name: Build MACOS

on:
  push:
    branches:
      - macos
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4

      - name: install appdmg
        run: sudo npm install -g appdmg

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Decode and install certificate
        env:
          CERTIFICATE_P12: ${{ secrets.MACOS_CERTIFICATE }}
        run: |
          echo "$CERTIFICATE_P12" | base64 --decode > certificate.p12
          security import certificate.p12 -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign

      - name: Build And Sign
        run: ./dmg-creator/build_macos.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOSApp
          path: build/macos/Build/Products/Release/Mostaqem.app
