name: Mostaqem
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_linux:
    name: Mostaqem Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: sudo apt-get update
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev rpm tree

      - run: flutter config --enable-linux-desktop

      - run: flutter pub get

      - run: flutter build linux --verbose

      - name: Build RPM Package
        run: |
          cp -fr build/linux/x64/release/bundle linux/debian/usr/share/mostaqem
          mkdir linux/debian/usr/bin
          ln -sr linux/debian/usr/share/mostaqem/mostaqem linux/debian/usr/bin/mostaqem
          sed -i "s:cp -rf :cp -rf $(pwd)/:" linux/rpm/mostaqem.spec
          cd linux/debian
          sed -i "s:FILES_HERE:$(find usr \( -type l -o -type f \) -follow -print | awk '{printf "/%s\\n", $0}'):" ../rpm/mostaqem.spec
          cd ../../
          rpmbuild -bb linux/rpm/mostaqem.spec -D "_topdir $(pwd)/rpmbuild"
          cp rpmbuild/RPMS/x86_64/*.rpm mostaqem-linux-x86_64.rpm

      - name: Build DEB Package
        run: |
          dpkg-deb --build --root-owner-group linux/debian
          cp linux/*.deb mostaqem-linux-x86_64.deb

      - name: Build Tarball
        run: |
          mkdir -p AppDir/
          cp -r linux/debian/usr AppDir/
          ln -sr AppDir/usr/bin/mostaqem AppDir/mostaqem
          tar czf mostaqem-linux-x86_64.tar.gz -C AppDir/ .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          body: ""
          files: mostaqem-linux-*
          token: ${{ secrets.PAT }}
          if: startsWith(github.ref, 'refs/tags/')
 