name: Deploying Manual
on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: Github release tag (vX.X.X.X)
        required: true
      version:
        type: string
        description: Mostaqem version (X.X.X)
        required: true
jobs:
  release_winget:
    name: Publishing to Winget
    runs-on: windows-latest
    steps:
    
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Mostaqem.Mostaqem
          installers-regex: '\.exe$'
          token: ${{ secrets.PAT }}
          version: ${{ inputs.version }}
          release-tag: ${{ inputs.release-tag }}
          fork-user: MezoPeeta
